# Generated by Django 4.1.7 on 2023-03-04 17:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('accType', models.CharField(choices=[('Customer', 'Customer'), ('Promoter', 'Promoter'), ('Vanue', 'Venue')], default='Customer', max_length=10, verbose_name='Account Type')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concertName', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 3, 4, 12, 13, 33, 918996), verbose_name='Concert Date')),
            ],
        ),
        migrations.CreateModel(
            name='VenueOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='frontapp.accounttype')),
                ('venueName', models.CharField(default='', max_length=150, null=True, verbose_name='Venue Name')),
            ],
        ),
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managed_concerts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontapp.concert', verbose_name='Concerts/Events Managed')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontapp.accounttype')),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='venueName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontapp.venueowner', verbose_name='Venue'),
        ),
    ]
