# Generated by Django 4.1.7 on 2023-03-04 18:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 13, 14, 48, 460884), verbose_name='Concert Date'),
        ),
        migrations.AlterField(
            model_name='promoter',
            name='managed_concerts',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontapp.concert', verbose_name='Concerts/Events Managed'),
        ),
    ]
