# Generated by Django 4.1.7 on 2023-03-04 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0002_alter_concert_date_alter_promoter_managed_concerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 13, 19, 22, 276719), verbose_name='Concert Date'),
        ),
        migrations.AlterField(
            model_name='promoter',
            name='managed_concerts',
            field=models.ForeignKey(default='Please Pick a Venue', null=True, on_delete=django.db.models.deletion.CASCADE, to='frontapp.concert', verbose_name='Concerts/Events Managed'),
        ),
    ]
