# Generated by Django 4.1.7 on 2023-03-05 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0004_alter_concert_date_alter_promoter_managed_concerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueowner',
            name='num1',
            field=models.IntegerField(default=0, verbose_name='Number of Seats Available'),
        ),
        migrations.AddField(
            model_name='venueowner',
            name='num2',
            field=models.IntegerField(default=0, verbose_name='Number of Seats Available'),
        ),
        migrations.AddField(
            model_name='venueowner',
            name='num3',
            field=models.IntegerField(default=0, verbose_name='Number of Seats Available'),
        ),
        migrations.AddField(
            model_name='venueowner',
            name='num4',
            field=models.IntegerField(default=0, verbose_name='Number of Seats Available'),
        ),
        migrations.AddField(
            model_name='venueowner',
            name='seats1',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Seat Tier Name'),
        ),
        migrations.AddField(
            model_name='venueowner',
            name='seats2',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Seat Tier 2 Name'),
        ),
        migrations.AddField(
            model_name='venueowner',
            name='seats3',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Seat Tier 3 Name'),
        ),
        migrations.AddField(
            model_name='venueowner',
            name='seats4',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Seat Tier 4 Name'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 1, 45, 18, 781110), verbose_name='Concert Date'),
        ),
    ]
