# Generated by Django 4.1.7 on 2023-03-05 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0005_venueowner_num1_venueowner_num2_venueowner_num3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='accType',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Promoter', 'Promoter'), ('Venue', 'Venue')], default='Customer', max_length=10, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 1, 55, 47, 207728), verbose_name='Concert Date'),
        ),
    ]
