# Generated by Django 4.1.7 on 2023-03-05 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0008_alter_concert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueowner',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='venueowner',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='venueowner',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='venueowner',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 3, 16, 24, 11213), verbose_name='Concert Date'),
        ),
    ]
