# Generated by Django 4.1.7 on 2023-03-05 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0009_venueowner_price1_venueowner_price2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 3, 17, 29, 899513), verbose_name='Concert Date'),
        ),
    ]
