# Generated by Django 4.1.7 on 2023-03-05 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0010_alter_concert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 3, 20, 42, 94638), verbose_name='Concert Date'),
        ),
        migrations.AlterField(
            model_name='venueowner',
            name='seats2',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Seat Tier 2 Name'),
        ),
        migrations.AlterField(
            model_name='venueowner',
            name='seats3',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Seat Tier 3 Name'),
        ),
        migrations.AlterField(
            model_name='venueowner',
            name='seats4',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Seat Tier 4 Name'),
        ),
    ]
