# Generated by Django 4.1.7 on 2023-03-05 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0011_alter_concert_date_alter_venueowner_seats2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 3, 21, 32, 290737), verbose_name='Concert Date'),
        ),
        migrations.AlterField(
            model_name='venueowner',
            name='seats1',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Seat Tier Name'),
        ),
    ]
