# Generated by Django 4.1.7 on 2023-03-05 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0012_alter_concert_date_alter_venueowner_seats1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 4, 12, 54, 721700), verbose_name='Concert Date'),
        ),
        migrations.AlterField(
            model_name='venueowner',
            name='num1',
            field=models.IntegerField(default=0, verbose_name='Total Seats'),
        ),
        migrations.AlterField(
            model_name='venueowner',
            name='num2',
            field=models.IntegerField(default=0, verbose_name='Total Seats'),
        ),
        migrations.AlterField(
            model_name='venueowner',
            name='num3',
            field=models.IntegerField(default=0, verbose_name='Total Seats'),
        ),
        migrations.AlterField(
            model_name='venueowner',
            name='num4',
            field=models.IntegerField(default=0, verbose_name='Total Seats'),
        ),
    ]
