# Generated by Django 4.1.7 on 2023-03-05 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0013_alter_concert_date_alter_venueowner_num1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 4, 13, 0, 623511), verbose_name='Concert Date'),
        ),
    ]
