# Generated by Django 4.1.7 on 2023-03-05 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0015_alter_concert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 5, 22, 28, 440337), verbose_name='Concert Date'),
        ),
        migrations.AlterField(
            model_name='venueowner',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Seat Price '),
        ),
        migrations.AlterField(
            model_name='venueowner',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Seat Price '),
        ),
        migrations.AlterField(
            model_name='venueowner',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Seat Price '),
        ),
        migrations.AlterField(
            model_name='venueowner',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Seat Price '),
        ),
    ]
