# Generated by Django 4.1.7 on 2023-03-05 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0016_alter_concert_date_alter_venueowner_price1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 5, 25, 30, 73710), verbose_name='Concert Date'),
        ),
    ]
