# Generated by Django 4.1.7 on 2023-03-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0023_alter_concert_date_alter_concert_venuename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='Concert Date'),
        ),
    ]
