# Generated by Django 4.1.7 on 2023-03-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0024_alter_concert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concert Date'),
        ),
    ]
