# Generated by Django 4.1.7 on 2023-03-05 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0028_alter_concert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 8, 33, 26, 635033), verbose_name='Concert Date'),
        ),
    ]
