# Generated by Django 4.1.7 on 2023-03-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0029_alter_concert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='time',
            field=models.TimeField(null=True, verbose_name='Concert Time'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Concert Date'),
        ),
    ]
