# Generated by Django 4.1.7 on 2023-03-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0033_alter_concert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(null=True, verbose_name='Concert Date'),
        ),
    ]
