# Generated by Django 4.1.7 on 2023-03-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0035_concert_seats1_avail_concert_seats2_avail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='seat_type',
            field=models.IntegerField(default=1),
        ),
    ]
