# Generated by Django 4.1.7 on 2023-03-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0038_rename_seats1_avail_concert_seats_avail1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venueowner',
            old_name='seats_avail1',
            new_name='seats_capacity1',
        ),
        migrations.RenameField(
            model_name='venueowner',
            old_name='seats_avail2',
            new_name='seats_capacity2',
        ),
        migrations.RenameField(
            model_name='venueowner',
            old_name='seats_avail3',
            new_name='seats_capacity3',
        ),
        migrations.RenameField(
            model_name='venueowner',
            old_name='seats_avail4',
            new_name='seats_capacity4',
        ),
    ]
