# Generated by Django 4.1.7 on 2023-03-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0039_rename_seats_avail1_venueowner_seats_capacity1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Seat Price '),
        ),
    ]
