# Generated by Django 4.1.7 on 2023-03-06 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0040_ticketorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontapp.accounttype'),
        ),
    ]
